#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Merge default rules
  merge-default-rules: true

rules:
  no-empty-rulesets: 1
  no-ids: 0
  no-url-protocols: 0
  no-url-domains: 0
  no-color-hex: 0
  no-mergeable-selectors: 1
  quotes: 0

  # Name format
  class-name-format: 1
  function-name-format: 1
  id-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  color-hex-length: 0

